const plans={
  plan1:{title:'案1 · 王道の往復',tag:'短め・移動を絞る',duration:'航空券＋バス＋国内移動',price:'15.4',overseas:'航空券 約15.4万円',return:'新幹線・未入力',returnLabel:'新幹線',returnText:'日本到着後は新幹線で名古屋へ。料金と終電はあとで追加します。',segments:[['名古屋','東京','高速バス'],['東京','ザグレブ','飛行機'],['ザグレブ','ドゥブロブニク','飛行機'],['ドゥブロブニク','ザグレブ','飛行機'],['ザグレブ','リュブリャナ','バス'],['リュブリャナ','ザグレブ','バス'],['ザグレブ','日本','飛行機']],flights:[['1flight.png','東京 ⇄ ザグレブ','Air China / 経由便 / 約153,840円'],['2flight.png','航空券の選択画面','往路・復路の運賃メモ']],good:['ルートが比較的シンプルで、帰国後は新幹線に乗り継げる','ザグレブ往復航空券を軸に予定を立てやすい'],bad:['都市間移動が往復になり、同じ区間を戻る','乗り継ぎの待ち時間と荷物の確認が必要']},
  plan2:{title:'案2 · 滞在を伸ばす',tag:'日数を増やしてゆっくり',duration:'案1＋追加滞在',price:'15.3',overseas:'航空券 約15.3万円',return:'新幹線・未入力',returnLabel:'新幹線',returnText:'日本到着後は新幹線で名古屋へ。案1と同じ移動です。',segments:[['名古屋','東京','高速バス'],['東京','ザグレブ','飛行機'],['ザグレブ','ドゥブロブニク','飛行機'],['ドゥブロブニク','ザグレブ','飛行機'],['ザグレブ','リュブリャナ','バス'],['リュブリャナ','ザグレブ','バス'],['ザグレブ','日本','飛行機']],flights:[['1flight.png','東京 ⇄ ザグレブ','Air China / 経由便 / 約153,840円'],['2flight.png','航空券の選択画面','往路・復路の運賃メモ']],good:['同じルートで滞在日数を伸ばせる','観光と休息の余白をつくりやすい'],bad:['宿泊費・食費などの旅行総額は増える','長くなる分、帰国後の予定調整が必要']},
  plan3:{title:'案3 · ヴェネツィアまで進む',tag:'都市を一つ多く巡る',duration:'航空券＋欧州バス',price:'15.7',overseas:'航空券 約15.7万円〜',return:'大阪：ヤコバ／後泊・東京：新幹線',returnLabel:'大阪着：ヤコバ or 後泊 ／ 東京着：新幹線',returnText:'大阪着なら夜行バス（ヤコバ）か後泊、東京着なら新幹線で名古屋へ。',segments:[['名古屋','東京','高速バス'],['東京','ザグレブ','飛行機'],['ザグレブ','ドゥブロブニク','飛行機'],['ドゥブロブニク','ザグレブ','飛行機'],['ザグレブ','リュブリャナ','バス'],['リュブリャナ','ヴェネツィア','バス'],['ヴェネツィア','日本','飛行機']],flights:[['3-1flight.png','ヴェネツィア → 大阪','約156,910円 / 経由便'],['3-2flight.png','ヴェネツィア → 東京','約147,800円 / 経由便']],good:['帰りにヴェネツィアへ進み、移動の重複を減らせる','バスで国境を越える旅の思い出が増える'],bad:['大阪着の場合、夜行バスか後泊の判断が必要','都市間バスとフライトの接続を丁寧に確認する']}
};
const cards=[{id:'plan1',no:'PLAN 01',title:'王道の往復',desc:'ザグレブを拠点に、ドゥブロブニクとリュブリャナを往復する案。',route:'ZAG → DBV → ZAG → LJU → ZAG → JPN',days:'短め',return:'新幹線'},{id:'plan2',no:'PLAN 02',title:'滞在を伸ばす',desc:'案1のルートをベースに、現地で過ごす日数を増やす案。',route:'ZAG → DBV → ZAG → LJU → ZAG → JPN',days:'長め',return:'新幹線'},{id:'plan3',no:'PLAN 03',title:'ヴェネツィアまで',desc:'リュブリャナからバスでヴェネツィアへ進み、帰国する案。',route:'ZAG → DBV → ZAG → LJU → VCE → JPN',days:'周遊型',return:'ヤコバ／後泊'}];
document.getElementById('planCards').innerHTML=cards.map(c=>`<article class="plan-card" data-card="${c.id}"><span class="plan-no">${c.no}</span><h3>${c.title}</h3><p class="plan-desc">${c.desc}</p><p class="route-line">${c.route.split(' → ').map((x,i)=>i<c.route.split(' → ').length-1?`${x}<span>→</span>`:x).join('')}</p><div class="card-stats"><div><span class="stat-label">滞在イメージ</span><b class="stat-value">${c.days}</b></div><div><span class="stat-label">帰国後</span><b class="stat-value">${c.return}</b></div></div><button class="card-link" data-select="${c.id}">詳しく見る</button></article>`).join('');
const els={title:document.getElementById('detailTitle'),tag:document.getElementById('detailTag'),duration:document.getElementById('detailDuration'),price:document.getElementById('detailPrice'),overseas:document.getElementById('detailOverseas'),ret:document.getElementById('detailReturn'),returnLabel:document.getElementById('returnLabel'),returnText:document.getElementById('returnText'),timeline:document.getElementById('timeline'),flightGrid:document.getElementById('flightGrid'),good:document.getElementById('goodList'),bad:document.getElementById('badList'),map:document.getElementById('routeMap')};
function showPlan(id){const p=plans[id];els.title.textContent=p.title;els.tag.textContent=p.tag;els.duration.textContent=p.duration;els.price.innerHTML=`約${p.price}<span>万円〜</span>`;els.overseas.textContent=p.overseas;els.ret.textContent=p.return;els.returnLabel.textContent=p.returnLabel;els.returnText.textContent=p.returnText;els.timeline.innerHTML=p.segments.map(s=>`<div class="segment"><div class="segment-place"><b>${s[0]}</b></div><div class="segment-line"><span class="mode">${s[2]}</span><span class="line-arrow">→</span></div><div class="segment-place"><b>${s[1]}</b></div></div>`).join('');els.flightGrid.innerHTML=p.flights.map(f=>`<button class="flight-card" data-src="assets/${f[0]}" data-alt="${f[1]}"><img src="assets/${f[0]}" alt="${f[1]}" loading="lazy"><span><strong>${f[1]}</strong><small>${f[2]}</small></span></button>`).join('');els.good.innerHTML=p.good.map(x=>`<li>${x}</li>`).join('');els.bad.innerHTML=p.bad.map(x=>`<li>${x}</li>`).join('');els.map.innerHTML=p.segments.map(s=>`<span class="map-stop"><b>${s[0]}</b><small>${s[2]}</small></span>`).concat([`<span class="map-stop"><b>${p.segments.at(-1)[1]}</b><small>到着</small></span>`]).join('');document.querySelectorAll('.switch').forEach(b=>{const active=b.dataset.plan===id;b.classList.toggle('active',active);b.setAttribute('aria-selected',active)});document.querySelectorAll('.plan-card').forEach(c=>c.classList.toggle('selected',c.dataset.card===id))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b){showPlan(b.dataset.select);document.getElementById('routes').scrollIntoView({behavior:'smooth',block:'start'})}const s=e.target.closest('.switch');if(s)showPlan(s.dataset.plan)});showPlan('plan1');
const gallery=[['1flight.png','flight','案1 · 往復航空券','東京 ⇄ ザグレブ / Air China'],['2flight.png','flight','案1／案2 · 選択画面','往路・復路の運賃メモ'],['3-1flight.png','flight','案3 · 大阪着','ヴェネツィア → 大阪 / 約156,910円'],['3-2flight.png','flight','案3 · 東京着','ヴェネツィア → 東京 / 約147,800円'],['3toDBV.png','ground','案3 · ザグレブ→ドゥブロブニク','飛行機 / 約7,897円〜'],['3toZAG.png','ground','案3 · ドゥブロブニク→ザグレブ','飛行機 / 約7,897円〜'],['3bus-1.png','ground','案3 · ザグレブ→リュブリャナ','バス / FlixBus €12〜'],['3bus-2.png','ground','案3 · リュブリャナ→ヴェネツィア','バス / FlixBus €20〜']];
function renderGallery(filter='all'){document.getElementById('galleryGrid').innerHTML=gallery.filter(x=>filter==='all'||x[1]===filter).map(x=>`<button class="gallery-item" data-src="assets/${x[0]}" data-alt="${x[2]}"><img src="assets/${x[0]}" alt="${x[2]}" loading="lazy"><span class="gallery-caption"><strong>${x[2]}</strong>${x[3]}</span></button>`).join('')};renderGallery();document.querySelectorAll('.gallery-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.gallery-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGallery(b.dataset.gallery)}));
const dialog=document.getElementById('imageDialog'),dialogImage=document.getElementById('dialogImage');document.addEventListener('click',e=>{const item=e.target.closest('.gallery-item,.flight-card');if(item){dialogImage.src=item.dataset.src;dialogImage.alt=item.dataset.alt;dialog.showModal()}});document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.getElementById('reykBudget').addEventListener('input',e=>{document.getElementById('reykTotal').textContent=e.target.value?`¥${Number(e.target.value).toLocaleString()}`:'未入力'});
